[tools]
"npm:prettier" = "latest"
"pipx:commitizen" = "latest"
ruff = "latest"
uv = "latest"

[env]
CZ_CONFIG = 'src/cz/cz.yaml'
UV_LINK_MODE = 'copy'

[tasks]
bump = "cz --config $CZ_CONFIG  bump"
commit = "cz --config $CZ_CONFIG commit"
changelog = "cz --config $CZ_CONFIG changelog"

[tasks.format]
description = "Format code layout"
run = "prettier --write ."

[tasks.lint]
description = "Lint and auto-fix code quality issues using Ruff"
run = "ruff check --fix"

# The "alias" that runs everything formatting and lint
[tasks.fmt]
description = "Fix lint errors and format all files"
run = [{ task = "lint" }, { task = "format" }]

[tasks.build]
description = "Build standalone executable using PyInstaller"
run = "uv run pyinstaller --onefile --name quikrun --paths src src/quikrun/main.py"

[tasks.tests]
description = "Run test suite"
run = "uv run pytest"