name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@8
        with:
          cache-python: true

      - name: Build
        run: uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
