name: Publish to PyPI
run-name: "Publish PyPI Package: ${{ github.ref_name }}"

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          cache-python: true
          activate-environment: "true"

      - name: Build
        run: uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
