name: Test Changes
run-name: Test Changes by ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          activate-environment: "true"
          restore-cache: "true"
          save-cache: "true"

      - name: Run tests
        run: |
          uv sync --dev
          uv run pytest tests/

      - name: Prune uv cache
        if: always()
        run: uv cache prune --ci
